name: bbVV
channels:
  - conda-forge
dependencies:
  - python=3.9
  - coffea=0.7.21
  - xrootd=5.4.0
  - pip
  - pip:
      - fastjet=3.4.0.1  # pre awkward v2, but doesn't work on mac!
      - pre-commit
      - black
      - pyyaml
      - tritonclient[all]