{
    "Training": {
        "HWWPrivate": {
            "subsamples": [
                "BulkGravitonToHHTo4W_JHUGen_MX-600to6000_MH-15to250_v2_ext1",
                "BulkGravitonToHHTo4W_JHUGen_MX-600to6000_MH-15to250_v2",
                "JHUVariableWMass_part1",
                "JHUVariableWMass_part2",
                "JHUVariableWMass_part3",
            ],
            "files_per_job": 20,
            "label": "_H_VV",
            "njets": 2,
        },
        "QCD": {
            "subsamples": [
                "QCD_Pt_300to470",
                "QCD_Pt_470to600",
                "QCD_Pt_600to800",
                "QCD_Pt_800to1000",
                "QCD_Pt_1000to1400",
            ],
            "files_per_job": 1,
            "label": "_QCD",
            "njets": 1,
            "maxchunks": 1,
            "chunksize": 800,
        },
        "WJetsToLNu": {
            "subsamples": [
                "WJetsToLNu_HT-200To400",
                "WJetsToLNu_HT-400To600",
                "WJetsToLNu_HT-600To800",
                "WJetsToLNu_HT-800To1200",
                "WJetsToLNu_HT-1200To2500",
                "WJetsToLNu_HT-2500ToInf",
            ],
            "files_per_job": 5,
            "label": "_VJets",
            "njets": 1,
        },
        "TTbar": {
            "subsamples": [
                "TTToSemiLeptonic",
                "TTToHadronic"
            ],
            "files_per_job": 2,
            "label": "_Top",
            "njets": 2,
            "maxchunks": 2,
        },
        "Hgg": {
            "subsamples": ["HJ_Nano2"],
            "files_per_job": 20,
            "label": "_H_qq",
            "njets": 1,
        }
    },
    "Validation": {
        "QCDHerwig": {
            "subsamples": [
                "QCD_Pt_150to3000_herwig"
            ],
            "files_per_job": 1,
            "label": "_QCD",
            "njets": 1,
            "maxchunks": 2,
        },
        "XHYPrivate": {
            "subsamples": [
                "NMSSM_XToYH_MX1600_MY100_HTo2bYTo2W_hadronicDecay",
                "NMSSM_XToYH_MX1600_MY125_HTo2bYTo2W_hadronicDecay",
                "NMSSM_XToYH_MX1600_MY190_HTo2bYTo2W_hadronicDecay",
                "NMSSM_XToYH_MX1600_MY300_HTo2bYTo2W_hadronicDecay",
                "NMSSM_XToYH_MX1600_MY600_HTo2bYTo2W_hadronicDecay",
                "NMSSM_XToYH_MX1600_MY900_HTo2bYTo2W_hadronicDecay",
            ],
            "files_per_job": 40,
            "label": "_Y_VV",
            "njets": 2,
        },
        "HWWPrivate": {
            "subsamples": [
                "GluGluToBulkGravitonToHHTo4W_JHUGen_M-2500_narrow",
            ],
            "files_per_job": 20,
            "label": "_H_VV",
            "njets": 2,
        },
        "HWW": {
            "subsamples": [
                "GluGluHToWW_Pt-200ToInf_M-125",
            ],
            "files_per_job": 2,
            "label": "_H_VV",
            "njets": 2,
        },
    },
}